name: Evaluate and Send Result             # <- Workflow name.

on:                                             # <- The trigger definition block.
  push:                                         # <- An event to trigger the action, of type push.
    branches: [                                 # <- Target Branches. Accepts an array.
      main, mmdet
    ]

jobs:                                           # <- The execution of work block.
  Job-Identifier:                               # <- Job ID. Contains related action steps.
    name: Evaluate          # <- Job Name.
    runs-on: self-hosted                     # <- Tells the server which OS to run on. Can also be windows, macOS, or even self-hosted.      

    steps:                                      # <- Step definitions.
      - uses: actions/checkout@v2               # <- Use keyword selects an action. Actions/ path in github is where common actions are predefined.
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Execute the run script for main.py
        run: ./run.sh

      - name: Read CSV Problem 1
        id: csv_pred
        uses: juliangruber/read-file-action@v1
        with:
          path: /workspace/SummerCamp2022/results/Problem_01/output-Problem_01.csv
      - uses: juliangruber/read-file-action@v1
        id: csv_gt
        with:
          path: /workspace/SummerCamp2022/data/output-Problem_01.csv
  
      - uses: petems/csv-to-md-table-action@v1.0.0
        id: csv-table-output_pred
        with:
          csvinput: ${{ steps.csv_pred.outputs.content }}
      - uses: petems/csv-to-md-table-action@v1.0.0
        id: csv-table-output_gt
        with:
          csvinput: ${{ steps.csv_gt.outputs.content }}
      - run: |
             echo "Problem 1 Ground Truth"  >> $GITHUB_STEP_SUMMARY
             echo "${{steps.csv-table-output_gt.outputs.markdown-table}}  \n\n" >> $GITHUB_STEP_SUMMARY
             echo "Problem 1 Predicted"  >> $GITHUB_STEP_SUMMARY
             echo  "${{steps.csv-table-output_pred.outputs.markdown-table}}"  >> $GITHUB_STEP_SUMMARY